### ISSUE TITLE
cst-python

### ISSUE THREAD

**Issue by TDCHH77** [pointm/PythonWithCST#1]
If you want to import HFSS files into CST during CST-python co-simulation, how to write a script, only the name of the imported file is in the history tree, and there is no path related to it

**Comment by pointm** [comment]
啊？这，要不你试试把文件名改成你模型的绝对路径？

**Comment by TDCHH77** [comment]
历史树中的脚本是这样记录的：With HFSS
     .Reset 
     .FilenameHFSS "*moxing.aedt" 
     .FilenameSM3 "*1.sm3" 
     .Id "1" 
     .Read 
End With

**Comment by pointm** [comment]
> 历史树中的脚本是这样记录的：With HFSS
>      .Reset 
>      .FilenameHFSS "*moxing.aedt" 
>      .FilenameSM3 "*1.sm3" 
>      .Id "1" 
>      .Read 
> End With

你的这个历史树的*号的意思是在你的整个硬盘范围内搜索历史树后面的这些文件名的文件，你把它改成文件的绝对路径试试

**Comment by TDCHH77** [comment]
> > 历史树中的脚本是这样记录的：With HFSS
> > .Reset
> > .FilenameHFSS "*moxing.aedt"
> > .FilenameSM3 "*1.sm3"
> > .Id "1"
> > .Read
> > End With
> 
> 你的这个历史树的*号的意思是在你的整个硬盘范围内搜索历史树后面的这些文件名的文件，你把它改成文件的绝对路径试试

I've tried to do this, but it still can't c'g ...

**Comment by TDCHH77** [comment]
> > 历史树中的脚本是这样记录的：With HFSS
> > .Reset
> > .FilenameHFSS "*moxing.aedt"
> > .FilenameSM3 "*1.sm3"
> > .Id "1"
> > .Read
> > End With
> 
> 你的这个历史树的*号的意思是在你的整个硬盘范围内搜索历史树后面的这些文件名的文件，你把它改成文件的绝对路径试试

I've tried to do this, but it still can't do it ，Can you give me a simple example of how to do this, thank you very much, I don't know right now if it's a problem with my code

**Comment by pointm** [comment]
> > > 历史树中的脚本是这样记录的：With HFSS
> > > .Reset
> > > .FilenameHFSS "*moxing.aedt"
> > > .FilenameSM3 "*1.sm3"
> > > .Id "1"
> > > .Read
> > > End With
> > 
> > 
> > 你的这个历史树的*号的意思是在你的整个硬盘范围内搜索历史树后面的这些文件名的文件，你把它改成文件的绝对路径试试
> 
> I've tried to do this, but it still can't do it ，Can you give me a simple example of how to do this, thank you very much, I don't know right now if it's a problem with my code

从官方的样例代码来看：
`Example

With HFSS

     .Reset

     .FilenameHFSS "*my_model.hfss"

     .FilenameSM3 "*my_model.sm3"

     .Filename "*my_model.sat"

     .Read

End With`
FilenameHFSS这个HFSS下属的方法貌似只能导入以`.hfss`为结尾的文件，要不使用`.hfss`为结尾的文件进行导入试试？

**Comment by TDCHH77** [comment]
> > > > 历史树中的脚本是这样记录的：With HFSS
> > > > .Reset
> > > > .FilenameHFSS "*moxing.aedt"
> > > > .FilenameSM3 "*1.sm3"
> > > > .Id "1"
> > > > .Read
> > > > End With
> > > 
> > > 
> > > 你的这个历史树的*号的意思是在你的整个硬盘范围内搜索历史树后面的这些文件名的文件，你把它改成文件的绝对路径试试
> > 
> > 
> > I've tried to do this, but it still can't do it ，Can you give me a simple example of how to do this, thank you very much, I don't know right now if it's a problem with my code
> 
> 从官方的样例代码来看： `Example
> 
> With HFSS
> 
> ```
>  .Reset
> 
>  .FilenameHFSS "*my_model.hfss"
> 
>  .FilenameSM3 "*my_model.sm3"
> 
>  .Filename "*my_model.sat"
> 
>  .Read
> ```
> 
> End With` FilenameHFSS这个HFSS下属的方法貌似只能导入以`.hfss`为结尾的文件，要不使用`.hfss`为结尾的文件进行导入试试？

当我导入dxf文件时，添加绝对路径是可以正常导入的，但是HFSS模型却不可以，我可以添加你的联系方式来让您了解一下详细错误吗，我愿意付报酬给你

**Comment by pointm** [comment]
> > > > > 历史树中的脚本是这样记录的：With HFSS
> > > > > .Reset
> > > > > .FilenameHFSS "*moxing.aedt"
> > > > > .FilenameSM3 "*1.sm3"
> > > > > .Id "1"
> > > > > .Read
> > > > > End With
> > > > 
> > > > 
> > > > 你的这个历史树的*号的意思是在你的整个硬盘范围内搜索历史树后面的这些文件名的文件，你把它改成文件的绝对路径试试
> > > 
> > > 
> > > I've tried to do this, but it still can't do it ，Can you give me a simple example of how to do this, thank you very much, I don't know right now if it's a problem with my code
> > 
> > 从官方的样例代码来看： `Example
> > 
> > With HFSS
> > 
> > ```
> >  .Reset
> > 
> >  .FilenameHFSS "*my_model.hfss"
> > 
> >  .FilenameSM3 "*my_model.sm3"
> > 
> >  .Filename "*my_model.sat"
> > 
> >  .Read
> > ```
> > 
> > End With` FilenameHFSS这个HFSS下属的方法貌似只能导入以`.hfss`为结尾的文件，要不使用`.hfss`为结尾的文件进行导入试试？
> 
> 当我导入dxf文件时，添加绝对路径是可以正常导入的，但是HFSS模型却不可以，我可以添加你的联系方式来让您了解一下详细错误吗，我愿意付报酬给你

感谢您对我所建议的方法的尝试与及时回复，但是非常抱歉的是我也不是很了解hfss相关的事情，我主要的仿真软件是cst，非常抱歉无法帮助到您

**Comment by TDCHH77** [comment]
> > > > > > 历史树中的脚本是这样记录的：With HFSS
> > > > > > .Reset
> > > > > > .FilenameHFSS "*moxing.aedt"
> > > > > > .FilenameSM3 "*1.sm3"
> > > > > > .Id "1"
> > > > > > .Read
> > > > > > End With
> > > > > 
> > > > > 
> > > > > 你的这个历史树的*号的意思是在你的整个硬盘范围内搜索历史树后面的这些文件名的文件，你把它改成文件的绝对路径试试
> > > > 
> > > > 
> > > > I've tried to do this, but it still can't do it ，Can you give me a simple example of how to do this, thank you very much, I don't know right now if it's a problem with my code
> > > 
> > > 
> > > 从官方的样例代码来看： `Example
> > > With HFSS
> > > ```
> > >  .Reset
> > > 
> > >  .FilenameHFSS "*my_model.hfss"
> > > 
> > >  .FilenameSM3 "*my_model.sm3"
> > > 
> > >  .Filename "*my_model.sat"
> > > 
> > >  .Read
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > End With` FilenameHFSS这个HFSS下属的方法貌似只能导入以`.hfss`为结尾的文件，要不使用`.hfss`为结尾的文件进行导入试试？
> > 
> > 
> > 当我导入dxf文件时，添加绝对路径是可以正常导入的，但是HFSS模型却不可以，我可以添加你的联系方式来让您了解一下详细错误吗，我愿意付报酬给你
> 
> 感谢您对我所建议的方法的尝试与及时回复，但是非常抱歉的是我也不是很了解hfss相关的事情，我主要的仿真软件是cst，非常抱歉无法帮助到您

非常感谢，从你这里我受到了启发，使用了另一种方式完成了上述操作
